### ISSUE TITLE
Some errors/ things that can be improved

### ISSUE THREAD

**Issue by maringernina** [5ahmnm2122/09CandyGame-lhell#3]
- Die Steuerung könnte noch verbessert werden; Spongebob weniger "herumsliden" lassen

- leeres Script "Result"

- Man kann trotzdem das Spiel starten obwohl kein Name eingegeben wurde

- NullReferenceException beim "GameManager" und "SaveData" Script

- Im "PlayerMovement" ungenutzte Start Methode

**Comment by HellLisa** [comment]
fixed Spongebob sliding too much

**Comment by HellLisa** [comment]
deleted useless/empty script

**Comment by HellLisa** [comment]
Fixed Name -> Can't start Game now without entering a name

**Comment by HellLisa** [comment]
fixed NullReferenceException by using PlayerPrefs right :^)
